### ISSUE TITLE
Stuck wenn gegner am ende vom Spielfeld :>

### ISSUE THREAD

**Issue by Martinuuu** [Timer2222/Schach#1]
pls fix

**Comment by Martinuuu** [comment]
![Alt Text](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2F31.media.tumblr.com%2Ftumblr_li9nogR9Wv1qhjikro1_500.gif&f=1&nofb=1&ipt=d749f1a63f21d44efebad14476f61c7a66a7d2ff2ec2dee1957ed32aea49ad24&ipo=images)

**Comment by Ayzzzzzzzzzzz** [comment]
ja selbes problrm bitte sofort fixen
